# Generated by Django 4.1.7 on 2023-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='acronym',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
