# Generated by Django 4.1.7 on 2023-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_university_acronym_alter_university_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
