# Generated by Django 4.1.7 on 2023-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_university_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='established_year',
            field=models.CharField(max_length=10),
        ),
    ]
